/// Maps server country names (Persian / English / ISO) to bundled flag
/// assets. Returns the asset path, or null when no flag is known and the
/// caller should fall back to a generic icon.
String? countryFlagAsset(String name) {
  final normalized = name.trim();
  if (normalized.isEmpty) return null;
  final key = normalized.toLowerCase();
  final mapped = _flagByName[key];
  if (mapped != null) return 'assets/flags/$mapped.png';
  // Bare ISO codes (JP, US, ...) pass through directly.
  if (RegExp(r'^[a-z]{2}$').hasMatch(key)) return 'assets/flags/$key.png';
  return null;
}

const _flagByName = <String, String>{
  // Persian names.
  'آمریکا': 'us',
  'چین': 'cn',
  'ژاپن': 'jp',
  'کره ای': 'kr',
  'کره حنوبی': 'kr',
  'نپال': 'np',
  'تایلند': 'th',
  'هند': 'in',
  'فرانسه': 'fr',
  'ایتالیا': 'it',
  'آلمان': 'de',
  'کانادا': 'ca',
  'دانمارک': 'dk',
  'انگلیس': 'gb',
  'هنگ کنگ': 'hk',
  'امارات': 'ae',
  'استرالیا': 'au',
  'روسیه': 'ru',
  'سوئد': 'se',
  'اسپانیا': 'es',
  // English names.
  'america': 'us',
  'usa': 'us',
  'united states of america': 'us',
  'china': 'cn',
  'japan': 'jp',
  'korea': 'kr',
  'south korea': 'kr',
  'nepal': 'np',
  'thailand': 'th',
  'india': 'in',
  'france': 'fr',
  'italy': 'it',
  'germany': 'de',
  'canada': 'ca',
  'denmark': 'dk',
  'england': 'gb',
  'britain': 'gb',
  'uk': 'gb',
  'united kingdom': 'gb',
  'hong kong': 'hk',
  'emirates': 'ae',
  'united arab emirates': 'ae',
  'qatar': 'qa',
  'australia': 'au',
  'new zealand': 'nz',
  'russia': 'ru',
  'soviet union': 'ru',
  'sweden': 'se',
  'spain': 'es',
  'brazil': 'br',
  'iran': 'ir',
  'israel': 'il',
  'indonesia': 'id',
  'philippines': 'ph',
  'peru': 'pe',
  'mexico': 'mx',
  'hungary': 'hu',
  'chile': 'cl',
  'argentina': 'ar',
  'egypt': 'eg',
  'croatia': 'hr',
  'switzerland': 'ch',
  'tunisia': 'tn',
  'belgium': 'be',
  'bangladesh': 'bd',
  'malaysia': 'my',
  'south africa': 'za',
  'bulgaria': 'bg',
  'netherlands': 'nl',
  'malta': 'mt',
  'taiwan': 'tw',
  'iceland': 'is',
  'norway': 'no',
  'estonia': 'ee',
  'serbia': 'rs',
  'yugoslavia': 'rs',
  'morocco': 'ma',
  'ireland': 'ie',
  'turkey': 'tr',
  'austria': 'at',
  'romania': 'ro',
  'czech republic': 'cz',
  'czech': 'cz',
  'poland': 'pl',
  'bahamas': 'bs',
  'algeria': 'dz',
  'colombia': 'co',
  'cambodia': 'kh',
  'ukraine': 'ua',
  'bosnia and herzegovina': 'ba',
  'ghana': 'gh',
  'jamaica': 'jm',
  'macedonia': 'mk',
  'dominican republic': 'do',
  'guatemala': 'gt',
  'greece': 'gr',
  'luxembourg': 'lu',
  'mongolia': 'mn',
  'macao': 'mo',
  'kazakhstan': 'kz',
  'fiji': 'fj',
  'portugal': 'pt',
  'cyprus': 'cy',
  'kenya': 'ke',
  'syrian arab republic': 'sy',
  'finland': 'fi',
  'slovakia': 'sk',
  'uruguay': 'uy',
  'paraguay': 'py',
  'slovenia': 'si',
  'palau': 'pw',
  'vietnam': 'vn',
  'rwanda': 'rw',
  'senegal': 'sn',
  'singapore': 'sg',
  'belarus': 'by',
  'botswana': 'bw',
  'georgia': 'ge',
  "cote d'ivoire": 'ci',
  'venezuela': 've',
  'kuwait': 'kw',
  'lebanon': 'lb',
  'libyan arab jamahiriya': 'ly',
  'saudi arabia': 'sa',
  'mauritania': 'mr',
  'puerto rico': 'pr',
  'latvia': 'lv',
  'pakistan': 'pk',
  'palestinian territory': 'ps',
  'albania': 'al',
  'jordan': 'jo',
};
